### ISSUE TITLE
Log Action Payload Event

### ISSUE THREAD

**Issue by autolog** [FlyingDiver/Indigo-Shims#10]
It would be nice if the there was an option for the Shims plugin to write an entry to the standard Indigo Event log (non-debug) to say e.g. 'Sent "Salus_Plug_1" on' when the Indigo device on button is pressed and likewise for OFF (when the plugin actions the specified ACTION Template). Rather like Indigo does for Z-Wave devices.  :)

**Comment by FlyingDiver** [comment]
In 0.2.3.
