### ISSUE TITLE
Write device template to log error

### ISSUE THREAD

**Issue by Highsteads** [FlyingDiver/Indigo-Shims#11]
Trying out the new shims branch and get an error when trying to write to log

`27 Feb 2020 at 11:31:06
   MQTT Shims Error                Error in plugin execution UiValidate:

Traceback (most recent call last):
  File "plugin.py", line 809, in dumpYAML
AttributeError: 'ServerStartupTrigger' object has no attribute 'pluginId'
`

**Comment by FlyingDiver** [comment]
Fixed in latest commit.
