### ISSUE TITLE
Period instead of comma

### ISSUE THREAD

**Issue by AaronLionsheep** [FlyingDiver/Indigo-Shims#12]
https://github.com/FlyingDiver/Indigo-Shims/blob/0b31ddc06f6f42fa745791bbba19dad4007993f0/MQTT%20Shims.indigoPlugin/Contents/Server%20Plugin/plugin.py#L67

There is a period instead of a comma in the format parameters.

**Comment by FlyingDiver** [comment]
Fixed in next release.
