### ISSUE TITLE
states list getting updated every message

### ISSUE THREAD

**Issue by kmarkley** [FlyingDiver/Indigo-Shims#19]
I've noticed for many of my shim devices, that `device.replacePluginPropsOnServer` and `device.stateListOrDisplayStateIdChanged` are being called every time a new MQTT message is received, even if there is no change to the device's states.  

This is not just unnecessary, it also causes `deviceUpdated` to be called twice for the device in plugin triggers (the in-built 'has any change' trigger appears to avoid this gracefully).

The issue seems to just be about list order.  Replacing `if old_states != new_states:` with `if set(old_states) != set(new_states):` corrects the problem.

Thanks

**Comment by FlyingDiver** [comment]
Interesting.  I'll take a look at that.

**Comment by kmarkley** [comment]
I've been poking around some more.  I don't think its the order of the list, but a peculiarity of indigo.List. I added this to the shims plugin code:
```            self.logger.info(u"indigo list compare: {}".format(old_states == new_states))
            self.logger.info(u"list compare: {}".format(list(old_states) == list(new_states)))
            self.logger.info(u"set compare: {}".format(set(old_states) == set(new_states)))```

And this is the result:
```   MQTT Shims                      indigo list compare: False
   MQTT Shims                      list compare: True
   MQTT Shims                      set compare: True```

**Comment by FlyingDiver** [comment]
So you think changing:
` ``
               if old_states != new_states:
```

To 
` ``
               if list(old_states) != list(new_states):
```
Would fix it?  Can you test that out?

**Comment by kmarkley** [comment]
`list` seems to work fine with the devices I'm looking at now.  But if you're going to coerce the indigo list to a new type anyway, you might as well use `set` which would continue to work even if the order of states were different for some reason.

**Comment by FlyingDiver** [comment]
Have you tested changing that line to `set`?

**Comment by kmarkley** [comment]
Yes, it works great

**Comment by FlyingDiver** [comment]
In 0.5.0.
