### ISSUE TITLE
Value Sensor device state triggers

### ISSUE THREAD

**Issue by HackintoshMan** [FlyingDiver/Indigo-Shims#2]
In the value sensor shim devices, there is an "On state" in the states field. I'm not sure if this should be here or not, but I think it is causing issues with creating a trigger for the device. 

Scenario:
Shim "Value Sensor" device with a multi-states key pulling multiple states for a payload.
If you try to create a "Device State Changed" trigger on the device, Indigo throws and `_updateDevStateKeyPopups` and doesn't let you create a trigger one anything other than an On/Off State change (which is then also broken).

Unable to create a value trigger for this device:
![Screen Shot 2019-08-10 at 11 28 57 PM](https://user-images.githubusercontent.com/3443748/62829228-06e3f700-bbc7-11e9-97bd-e9b65c612b77.png)

Able to create a value trigger for this device:
![Screen Shot 2019-08-10 at 11 29 16 PM](https://user-images.githubusercontent.com/3443748/62829232-195e3080-bbc7-11e9-99cb-ef18ee9425e5.png)

**Comment by FlyingDiver** [comment]
OK, I think I have this fixed for the next release.  It should work for new devices immediately.  For existing devices, you need to edit the device config at least once, and probably get an update from the hardware too.
