### ISSUE TITLE
error after update

### ISSUE THREAD

**Issue by kanutten** [FlyingDiver/Indigo-Shims#22]
Hi, 
I like this plugin alot :)
tried to update to 0.5.6 and get this error.
   

```
MQTT Shims Error                Error in plugin execution runConcurrentThread:

Traceback (most recent call last):
  File "plugin.py", line 115, in runConcurrentThread
  File "plugin.py", line 139, in processMessages
  File "plugin.py", line 328, in update
TypeError: object of type 'NoneType' has no len()

   MQTT Shims Error                plugin runConcurrentThread function returned or failed (will attempt again in 10 seconds)

```

**Comment by FlyingDiver** [comment]
All the time, even after restart?  Please turn on debug logging then post it.

**Comment by kanutten** [comment]
every 300sec, seems like I have a configuration issue.


 MQTT Shims Debug                wemos_bod_Dewpoint: states_dict = None
   MQTT Shims Error                wemos_bod_Dewpoint: Device config error, bad Multi-States Key value: AM2301
   MQTT Shims Error                Error in plugin execution runConcurrentThread:

Traceback (most recent call last):
  File "plugin.py", line 113, in runConcurrentThread
  File "plugin.py", line 137, in processMessages
  File "plugin.py", line 335, in update
TypeError: object of type 'NoneType' has no len()

   MQTT Shims Error                plugin runConcurrentThread function returned or failed (will attempt again in 10 seconds)

**Comment by FlyingDiver** [comment]
What's the MQTT payload look like?  It's almost certain that the multi-states key value should be blank or "." (meaning the top level of the dict).
