### ISSUE TITLE
Dimmer Device Image Status

### ISSUE THREAD

**Issue by kwijibo007** [FlyingDiver/Indigo-Shims#24]
The icon for Shims Dimmer devices in the Indigo Desktop Client and Indigo Touch never update to "on" - despite all other functionality working. 

It appears that calls for updateStateImageOnServer are missing on or around lines 436 & 438.

Adding them in per attachment resolves the issue.

![Capture](https://user-images.githubusercontent.com/17971944/180925231-1d0e3e97-efdc-4ade-bdcc-f65e74f015af.PNG)

**Comment by FlyingDiver** [comment]
Fixed for next release.
