### ISSUE TITLE
logs all log levels to file

### ISSUE THREAD

**Issue by berkinet** [FlyingDiver/Indigo-Shims#30]
Can no longer control log level for messages to file.  The plugin starts at logLevel=40.  Note the plugin is essentially non-responsive for any attempts to edit/create a device or include a device in a control page.  As a temporary measure to prevent the disk from filling up (it did this morning) I have linked com.flyingdiver.indigoplugin.shims/plugin.log to /dev/null

**Comment by FlyingDiver** [comment]
Fixed in 2023.0.3
