### ISSUE TITLE
Slow response or hang editing devices with Decoder references.

### ISSUE THREAD

**Issue by berkinet** [FlyingDiver/Indigo-Shims#31]
I discovered the cause of the slow response/hang problem when editing Shim devices, using the Decoder function. The device tag <states_list type="vector"> is continually extended to contain the Decoded values from the MQTT message. For example:
                                        <states_list type="vector">
                                                <Item type="string">data_format</Item>
                                                <Item type="string">humidity</Item>
                                                <Item type="string">temperature</Item>
                                                <Item type="string">pressure</Item>
                                                <Item type="string">acceleration</Item>
                                                <Item type="string">acceleration_x</Item>
                                                <Item type="string">acceleration_y</Item>
                                                <Item type="string">acceleration_z</Item>
                                                <Item type="string">tx_power</Item>
                                                <Item type="string">battery</Item>
                                                <Item type="string">movement_counter</Item>
                                                <Item type="string">measurement_sequence_number</Item>
                                                <Item type="string">mac</Item>
                                                 <Item type="string">data_format</Item>
                                                <Item type="string">humidity</Item>
                                                <Item type="string">temperature</Item>
                                                <Item type="string">pressure</Item>
                                                <Item type="string">acceleration</Item>
                                                <Item type="string">acceleration_x</Item>
                                                <Item type="string">acceleration_y</Item>
                                                <Item type="string">acceleration_z</Item>
                                                <Item type="string">tx_power</Item>
                                                <Item type="string">battery</Item>
                                                <Item type="string">movement_counter</Item>
                                                <Item type="string">measurement_sequence_number</Item>
                                                <Item type="string">mac</Item>
                                                ...
                                                ...
                                        </states_list>

**Comment by FlyingDiver** [comment]
Where is <states_list type="vector"> coming from?  The string  "vector" is not in the plugin code.

**Comment by berkinet** [comment]
Here is the device from the Indigi database.
[saved-shim-device.txt](https://github.com/FlyingDiver/Indigo-Shims/files/13465302/saved-shim-device.txt)

**Comment by FlyingDiver** [comment]
Oh, that's how the Indigo database saves a list.  I need to see your Decoder code.

**Comment by berkinet** [comment]
`from ruuvi_decoders import Df5Decoder

class Ruuvi(object):
    def __init__(self, name):
        self.name = name
        self.decoder = Df5Decoder()

    def decode(self, payload):
    
        new_states = {}
        decoder = Df5Decoder()
        ruuvi_data = payload['data']
        ruuvi_data = ruuvi_data.split("FF9904")[1]
        new_states = decoder.decode_data(ruuvi_data)
        if len(new_states):
            return new_states
        else:
            return None
`

**Comment by berkinet** [comment]
BTW, the list grows coincident with each processed message.

**Comment by FlyingDiver** [comment]
You're overloading the "decoder" name.  And creating a new Df5Decoder every time.

```
from ruuvi_decoders import Df5Decoder

class Ruuvi(object):
    def __init__(self, name):
        self.name = name
        self.df5decoder = Df5Decoder()

    def decode(self, payload):
    
        new_states = {}
        ruuvi_data = payload['data'].split("FF9904")[1]
        new_states = self.df5decoder.decode_data(ruuvi_data)
        if len(new_states):
            return new_states
        else:
            return None
```

**Comment by berkinet** [comment]
Ok. I see, I did not change the decoder reference to self.df5decoder...
Thanks.

**Comment by FlyingDiver** [comment]
I renamed it.

**Comment by berkinet** [comment]
Ah, ok. I missed that as the name was also used earlier in another context. Tested and it works.  <states_list> remains empty.

Thanks again.

**Comment by berkinet** [comment]
Unfortunately, the problem is back. I had waited several minutes after replacing the Decoder code and did not see the problem. However, while editing a control page just now I once again noticed a very sluggish response when opening the shim device to select a display state. On checking the IndigoDB I see the same issue I reported earlier.  For reference, here is the Decoder code:
`from ruuvi_decoders import Df5Decoder.

class Ruuvi(object):
    def __init__(self, name):
        self.name = name
        self.df5decoder = Df5Decoder()

    def decode(self, payload):
    
        new_states = {}
        ruuvi_data = payload['data'].split("FF9904")[1]
        new_states = self.df5decoder.decode_data(ruuvi_data)
        if len(new_states):
            return new_states
        else:
            return None`

**Comment by FlyingDiver** [comment]
Turn on debug logging and post the log section from when the issue happens.

**Comment by berkinet** [comment]
One possibility... When I loaded the newest plugin (from the plugin store) I did not at first realize you had moved the Decoders directory to the Python3-includes directory. So, I tried adding the decoder code to the Decoder directory embedded in the plugin.  That was the code with the overloaded reference.  I have now removed that file. However, is it possible the plugin for some reason, at some point, read that file instead?

**Comment by FlyingDiver** [comment]
But it's possible that since the old path was already saved to the device, it might have used it.  You can't select that location anymore.

**Comment by berkinet** [comment]
Here is the debug file from around when the plugin added new entries to the states_list.  What is weird is this does not happen on every message processed.  One other possible factor. I have two separate shim devices for the ruuvi tags. They differ on the second part of the topic (the mac address of the tag). However, both devices use the same code.
[shim_debug.txt](https://github.com/FlyingDiver/Indigo-Shims/files/13467047/shim_debug.txt)

**Comment by FlyingDiver** [comment]
I don't see anything unusual in that log.  I don't see any indication that the plugin is doing anything weird.

If the only problem you're seeing is the sluggish behavior when editing control pages, I'm inclined to attribute it to Indigo client issues with a device that's updating multiple times per second.  If you disable the trigger when doing your edits (so no updates are going to the Shims), does it behave?

**Comment by berkinet** [comment]
I am pretty sure the sluggish behavior is due to the very large size of the Device XML.  If I hand edit the DB (with the server not running) then it is snappy. But, over time, as the device size grows, it becomes increasingly sluggish.  Also,  I have 10 other shim devices and the sluggish behavior is only happening with the two shim devices that use the Decode option.

**Comment by FlyingDiver** [comment]
Hmm.  Do a right click on the shim device in the Indigo UI and print the device details to the log.  Then post that to this issue.

**Comment by berkinet** [comment]
I was trying to find the source of the problem, and did. Of course, I saved copies of the DB.  Attached is the device printout from the log.
[saved_device.txt](https://github.com/FlyingDiver/Indigo-Shims/files/13467097/saved_device.txt)

**Comment by berkinet** [comment]
One other thing, the error occurs at around 15 minute intervals.  I will delete and recreate the devices.

**Comment by FlyingDiver** [comment]
What do you mean?  You get an error message?  What happens every 15 minutes?

**Comment by berkinet** [comment]
I am monitoring the IndigoDB (grepping for a string that occurs in the additional states) once a minute.  When I see the could increase I know the error occurred

**Comment by berkinet** [comment]
I have deleted and replaced the two devices.  BTW, just in case this might have an impact, to limit the message volume, I am only enabling the MQTT connector device for 4 seconds every minute. I have it at 1 minute intervals now for testing.  Also, Ruuvi will be adding the ability to limit the message frequency so I won't have to do anything in Indigo.

**Comment by berkinet** [comment]
New device, same problem... 
[saved_device.txt](https://github.com/FlyingDiver/Indigo-Shims/files/13467160/saved_device.txt)

**Comment by berkinet** [comment]
I've installed the new version, so far so good. Out of curiosity, what was the problem?

**Comment by FlyingDiver** [comment]
There's a delay between when I update the state list on the server and when it'll return the new values to me.  The plugin host process caches the device def for a while.  So the plugin didn't see the updated states right away so it wasn't accounting for them properly.  I now do the merging of the existing states and the new states from the decoder differently.

**Comment by berkinet** [comment]
Thanks for the explanation, and thanks for the fix.  On Nov 26, 2023, at 17:06, Joe Keenan ***@***.***> wrote:﻿
There's a delay between when I update the state list on the server and when it'll return the new values to me.  The plugin host process caches the device def for a while.  So the plugin didn't see the updated states right away so it wasn't accounting for them properly.  I now do the merging of the existing states and the new states from the decoder differently.
