### ISSUE TITLE
Template .yaml experiment

### ISSUE THREAD

**Issue by whmoorejr** [FlyingDiver/Indigo-Shims#32]
I saw a post that said not many people have sent you template files to work with.... I took a crack at writing a .yaml file for an owntracks device.  I'm not sure if you can add states so they are always present?  Example, the states  "inregions" & "inrids" are only present if the device is inside of a geofence(region).  Otherwise, those two states aren't present on the device.
I though about dropping this as a .yaml file into the template folder and see what happens.... but I'm just making solid guesses with 1/2 of this and I'm not ready to break something that I just got working.  Anyway, this is what I have... might be useful if anyone else tries to use this platform.

`type: shimGeneric
message_type: '##OT##'
props:
    SupportsBatteryLevel: true
    SupportsStatusRequest : true
    battery_payload_key: batt
    reports_battery_status: true
    state_dict_payload_key: .
    state_location: payload
    state_location_payload_type: json
    uid_location: payload
    uid_location_payload_key: _type
    uid_location_topic_field: 2
    states_list :
        Item : sk_type
        Item : acc
        Item : alt
        Item : batt
        Item : bs
        Item : BSSID
        Item : conn
        Item : inregions
        Item : inrids
        Item : lat
        Item : lon
        Item : m
        Item : p
        Item : SSID
        Item : t
        Item : tid
        Item : tst
        Item : vac
    status_action_payload : '{"_type":"cmd","action":"reportLocation"}' 
    status_action_template : owntracks/{{uniqueID}}/cmd
trigger:
    match_list: '["Match: owntracks", "Match: Any"]'
    queueMessage: true
`
A couple notes:
Those are the correct states... not sure if they can be put in a template like that.
The devices use one of two unique ids (user and device)  All users have to be totally unique.  Device can be unique, but doesn't have to be.  Everyone can have "myphone" as their device.  owntracks/user/device/cmd   

cmd is used for publishing actions to the device... like a location report, loading geofences, and a few other things.  Owntracks/++/++/location is the main one to listen to.

**Comment by FlyingDiver** [comment]
You probably shouldn't try to hand-create a template.  You create templates using the menu command and specify a Shim device to use for the template.
