### ISSUE TITLE
Shim Trigger: Strange behavior

### ISSUE THREAD

**Issue by whmoorejr** [FlyingDiver/Indigo-Shims#33]
... Continued from our Indigodomo conversation...

I don't see anything in the log that even mentions the two triggers that didn't run...

The Trigger that worked is the "MQTT ..... Attempt 3"  Attempt 2 and the original one don't populate.  I don't even see them in the debug log.  If I toggle the triggers (disable/enable) I see them in the log...
```
Mar 5, 2024 at 2:37:24 PM
   MQTT Shims Debug                MQTT Event : Geofence Processing: Removing Trigger
   MQTT Shims Debug                MQTT Event : Geofence Processing: Adding Trigger
   MQTT Shims Debug                MQTT Event Processing: Geofence Attempt2: Removing Trigger
   MQTT Shims Debug                MQTT Event Processing: Geofence Attempt2: Adding Trigger
```
But if I publish a message under that topic... 

```
Mar 5, 2024 at 1:09:38 PM
   MQTT Connector Debug            MQTT Connector: logLevel = 10
   MQTT Shims Debug                logLevel = 5
   MQTT Connector Debug            Owntracks Broker: processReceivedMessage: owntracks/bill/myphone/event
   MQTT Connector Debug            MQTT Match Anna: type = topicMatch, broker = 1024070152
   MQTT Connector Debug            MQTT Match Anna: Matching complete, is_match = False
   MQTT Connector Debug            MQTT Match Bill: type = topicMatch, broker = 1024070152
   MQTT Connector Debug            MQTT Match Bill: Matching complete, is_match = False
   MQTT Connector Debug            MQTT Match CISA: type = topicMatch, broker = 1024070152
   MQTT Connector Debug            MQTT Match CISA: Matching complete, is_match = False
   MQTT Connector Debug            MQTT Match Harper: type = topicMatch, broker = 1024070152
   MQTT Connector Debug            MQTT Match Harper: Matching complete, is_match = False
   MQTT Connector Debug            MQTT Match IndigoServer: type = topicMatch, broker = 1024070152
   MQTT Connector Debug            MQTT Match IndigoServer: Matching complete, is_match = False
   MQTT Connector Debug            MQTT Match Vikki: type = topicMatch, broker = 1024070152
   MQTT Connector Debug            MQTT Match Vikki: Matching complete, is_match = False
   MQTT Connector Debug            MQTT Match All Events: type = topicMatch, broker = 1024070152
   MQTT Connector Debug            MQTT Match All Events: Matching complete, is_match = True
   Trigger                         MQTT Match All Events
   MQTT Shims Debug                message_handler: MQTT message ##allEvents## from Owntracks Broker
   MQTT Connector Debug            MQTT Match All CMD: type = topicMatch, broker = 1024070152
   MQTT Connector Debug            MQTT Match All CMD: Matching complete, is_match = False
   MQTT Shims Debug                MQTT-All Events: processMessages: '##allEvents##' owntracks/bill/myphone/event -> {"_type":"transition","acc":5,"desc":"Cline","event":"enter","lat": 28.123456,"lon":-95.123456,"rid":"my-region-id-002","t":"c","tid":"BM","tst":1709644520,"wtst":1708703481}
   MQTT Shims Debug                MQTT-All Events: multi_states_key= .
   MQTT Shims Debug                find_key_value key_string = '.', data_dict= {'_type': 'transition', 'acc': 5, 'desc': 'Cline', 'event': 'enter', 'lat': 28.123456, 'lon': -95.123456, 'rid': 'my-region-id-002', 't': 'c', 'tid': 'BM', 'tst': 1709644520, 'wtst': 1708703481}
   MQTT Shims Debug                find_key_value result = {'_type': 'transition', 'acc': 5, 'desc': 'Cline', 'event': 'enter', 'lat': 28.123456, 'lon': -95.123456, 'rid': 'my-region-id-002', 't': 'c', 'tid': 'BM', 'tst': 1709644520, 'wtst': 1708703481}
   MQTT Shims Debug                MQTT-All Events: multi_states_dict = {'_type': 'transition', 'acc': 5, 'desc': 'Cline', 'event': 'enter', 'lat': 28.123456, 'lon': -95.123456, 'rid': 'my-region-id-002', 't': 'c', 'tid': 'BM', 'tst': 1709644520, 'wtst': 1708703481}
   MQTT Shims Debug                MQTT-All Events: adding to state_updates: sk_type, transition, <class 'str'>
   MQTT Shims Debug                MQTT-All Events: adding to state_updates: acc, 5, <class 'int'>
   MQTT Shims Debug                MQTT-All Events: adding to state_updates: desc, Cline, <class 'str'>
   MQTT Shims Debug                MQTT-All Events: adding to state_updates: event, enter, <class 'str'>
   MQTT Shims Debug                MQTT-All Events: adding to state_updates: lat, 28.123456, <class 'float'>
   MQTT Shims Debug                MQTT-All Events: adding to state_updates: lon, -95.123456, <class 'float'>
   MQTT Shims Debug                MQTT-All Events: adding to state_updates: rid, my-region-id-002, <class 'str'>
   MQTT Shims Debug                MQTT-All Events: adding to state_updates: t, c, <class 'str'>
   MQTT Shims Debug                MQTT-All Events: adding to state_updates: tid, BM, <class 'str'>
   MQTT Shims Debug                MQTT-All Events: adding to state_updates: tst, 1709644520, <class 'int'>
   MQTT Shims Debug                MQTT-All Events: adding to state_updates: wtst, 1708703481, <class 'int'>
   Trigger                         MQTT Event: Geofence Processing Attempt 3
   Script                          At 2024-03-05 07:15:20 (1709644520), User: BM enter Cline
```

**Comment by FlyingDiver** [comment]
I forgot that the Shims plugin doesn't actually have any logging when processing triggers.  Some of my plugins do, this one doesn't.  

Attempt 3 is the Connector trigger, right?  Not  in the Shim?

I need to see screen shots of the Shim triggers.  I might need to add some debug statements if I can't spot the issue there.

**Comment by whmoorejr** [comment]
Attempt 3 is a generic "Device State Changed" trigger.  In that, I selected the shim "MQTT-All Events" and even selected the same state 'tst'  that Attempt 2 was looking at.  The first I just selected "Device Updated".

![Trigger1](https://github.com/FlyingDiver/Indigo-Shims/assets/24414574/53e74440-a418-4ce5-a87d-8444002f8d6a)
![Trigger2](https://github.com/FlyingDiver/Indigo-Shims/assets/24414574/5664cc93-524e-47e4-bcf6-2b5c1f53d098)

**Comment by FlyingDiver** [comment]
Please use the menu command to create a device template for that "MQTT-All Events" device and post it here.

**Comment by whmoorejr** [comment]
Here is the working trigger screen shot:
![Trigger3](https://github.com/FlyingDiver/Indigo-Shims/assets/24414574/ec0b8aba-3a76-4728-8d68-f1ece6758ac0)


From the top, this is the Connector match trigger for the shim.  I don't see any issues here.  The shim gets updated when a message under this topic shows up.
![Screenshot 2024-03-05 at 8 30 22 AM](https://github.com/FlyingDiver/Indigo-Shims/assets/24414574/1b7524b2-7216-4197-a94d-fd435ca53648)

From our other conversation (on indigodomo), I _could_ just add the action to this trigger.

**Comment by whmoorejr** [comment]
This?
`   MQTT Shims                      
message_type: '##allEvents##'
props:
    state_dict_payload_key: .
    state_location: payload
    state_location_payload_type: json
    uid_location: payload
    uid_location_payload_key: _type
    uid_location_topic_field: '0'
trigger:
    match_list: '["Match: owntracks", "Any: ", "Any: ", "Match: event", "End: "]'
    queueMessage: true
type: shimGeneric`

**Comment by FlyingDiver** [comment]
Yeah, that's what I need.  Still not seeing any issues.  I need to see if I can replicate.  Won't be today...

**Comment by FlyingDiver** [comment]
In the meantime, add the action to the connector trigger.

**Comment by whmoorejr** [comment]
Will do.  I'm in no rush on this.  I have a working solution, so I'm happy.  Any issue I've had so far I'm pretty sure has been user error on my end.  

Thank you again for the plugin.  I know I've been a pain to deal with.  My use of the plugin is a little different that others and I'm kinda an idiot.  :-)

**Comment by FlyingDiver** [comment]
You shim device has the UID (unique ID) defined as the value of the "_type" field in the payload:

    uid_location: payload
    uid_location_payload_key: _type

I can't see the value of that field, as it's not part of the template.  But I don't think that's correct.  So the MQTT message is probably not matching the Shim, so it's never even getting to the trigger tests.

**Comment by whmoorejr** [comment]
The message makes it to the shim... When the message is received, it does properly populate the shim with all the states from the JSON payload.  For this particular shim, I don't need the payload, except for troubleshooting.  The unique ID Value I set at "transition".  So far, ever time a "transition" message has gone through, my "3rd attempt" trigger picks up on the change to the shim  "tst" state (which is a unix timestamp of the message in the json payload).

Maybe I misread.  I was looking at unique... as in unique to the payload I want (to filter out messages I don't want).  

Did I find a way to booger up something?

**Comment by FlyingDiver** [comment]
Ok, so what you're doing definitely isn't how the plugin was designed to work, but it should work.

Found a bug that effected the Shim specific triggers for all generic devices.

https://github.com/FlyingDiver/Indigo-Shims/releases/tag/2023.2.1

**Comment by whmoorejr** [comment]
Got it.  That update fixed trigger #1 (which fires whenever the shim updates).
Trigger 2 did not fire and gave an error.  My guess (emphasize guess), a generic device doesn't have pre-defined states?

`   Trigger                         MQTT Event: Geofence Processing Attempt 3
   Trigger                         MQTT Event : Geofence Processing
   MQTT Shims Error                Error in plugin execution runConcurrentThread:

  File "plugin.py", line 148, in runConcurrentThread
  File "plugin.py", line 175, in processMessages
  File "plugin.py", line 649, in update
type: name 'states_dict' is not defined`

But to summarize, I now have 3 ways to trigger an action off a shim update:
Trigger added to shim match trigger
Indigo trigger: Device State Changed
and now:  MQTT Shims Event / Device Updated.

**Comment by FlyingDiver** [comment]
Correct, it does not.  Only what it finds in the multi-states field.  I'll need to find a way to block that error.

**Comment by whmoorejr** [comment]
> Ok, so what you're doing definitely isn't how the plugin was designed to work

I'm sure I'm not... but it's working great.  This piece, for example, starts with a message published by any one of 6 physical devices.  If one of those devices enters or leaves a geofence, they publish to the sub topic user/device/event (_type : "transition").  Around the same time, they publish user/device (_type : "location" with a payload that contains the location and name of geofence(s) they are in and some phone data.  This trigger (the one above) then runs a script that looks at the states of shim devices (one per physical phone) and tallies up who is in what geofence.  It then updates the variables of each Geofence device (from Variable Device plugin).  If there is someone in the fence, it turns on and another of the device states will list the names of who is in it.

I'm sure my phone shims are equally goofy with how they are set up... but they are working and I'm getting the data I want.  Your plugin was the only thing that could pull this all together for me.... for that I thank you!

It's all kinda hard to explain, but it's running pretty solid.  I'm just working on making it pretty and fine-tuning some of it.

**Comment by FlyingDiver** [comment]
Try https://github.com/FlyingDiver/Indigo-Shims/releases/tag/2023.2.2 for that last error message.

**Comment by whmoorejr** [comment]
Outstanding.  All of the triggers now work just fine with zero errors.  Thank you again sir.
