### ISSUE TITLE
update, unknown shimSensorSubtype: Luminance

### ISSUE THREAD

**Issue by WouterKr** [FlyingDiver/Indigo-Shims#4]
When sensor type Luminance (lux or %) is selected in a value sensor device the value of the device is not updated. Shims debug info:

   MQTT Shims Debug                received notification of MQTT message type ##sensors## from Algemeen - MQTT Broker
   MQTT Shims Debug                Buiten - Lichtsensor KapSchuur: processMessages: '##sensors##' devices/mqtt-KapSchuurLichtSensor/SENSOR -> {"Time":"2019-08-26T07:25:40","TSL2561":{"Illuminance":2244.000}}
   MQTT Shims Debug                Buiten - Lichtsensor KapSchuur: shimValueSensor, key = TSL2561.Illuminance, data = {u'TSL2561': {u'Illuminance': 2244.0}, u'Time': u'2019-08-26T07:25:40'}, value = 2244.0
   MQTT Shims Debug                Buiten - Lichtsensor KapSchuur: Updating state to 67320.0
   **MQTT Shims Debug                Buiten - Lichtsensor KapSchuur: update, unknown shimSensorSubtype: Luminance**

**Comment by FlyingDiver** [comment]
Try https://github.com/FlyingDiver/Indigo-Shims/releases/tag/0.1.1

**Comment by WouterKr** [comment]
Yes, solved! The illuminance sensor types (lux and %) are working now.

**Comment by FlyingDiver** [comment]
Release 0.1.1
